# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Deploy React Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code. # Repo checkout
        uses: actions/checkout@v3

      - name: Check Node v # Node v 확인
        run: node -v

      - name: Install Dependencies # 의존 파일 설치
        run: npm install

      - name: Build # React Build
        run: CI=false npm run build-prod

      - name: zip create # 효율적인 공간 활용을 위해 필요한 파일만 압축
        run: zip -qq -r ./build-gt-${{ secrets.NICKNAME }}-${{ secrets.GRIDGE_TEST_ID }}.zip ./build ./appspec.yml
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3 # Upload build file to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --region ap-northeast-2 ./build-gt-${{ secrets.NICKNAME }}-${{ secrets.GRIDGE_TEST_ID }}.zip s3://gridge-test/${{ secrets.NICKNAME }}-${{ secrets.GRIDGE_TEST_ID }}/build-gt-${{ secrets.NICKNAME }}-${{ secrets.GRIDGE_TEST_ID }}.zip

      - name: Deploy # Deploy to EC2
        run: aws deploy create-deployment
          --application-name gridge-test-codedeploy-app
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name gridge-test-codedeploy-deployment-group-${{ secrets.NICKNAME }}-${{ secrets.GRIDGE_TEST_ID }}
          --s3-location bucket=gridge-test,key=${{ secrets.NICKNAME }}-${{ secrets.GRIDGE_TEST_ID }}/build-gt-${{ secrets.NICKNAME }}-${{ secrets.GRIDGE_TEST_ID }}.zip,bundleType=zip
